# Generated by Django 3.1.5 on 2021-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210327_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionlist',
            name='username',
        ),
        migrations.AddField(
            model_name='optionlist',
            name='options_post_answers',
            field=models.TextField(null=True),
        ),
    ]
